image: node:5

stages:
  - tests

before_script:
    - cd src && npm install

Unit_tests:
  variables:
    MONGO_URL: "mongodb://mongo/3dptoolstests"
  stage: tests
  services:
    - mongo
  script:
    - npm t