image: node:5

stages:
  - tests
  - build
  - release
  - mirror

cache:
  key: 3dptools-ci
  paths:
  - src/node_modules
  - src/public/vendor

Unit tests:
  variables:
    MONGO_URL: "mongodb://mongo/3dptoolstests"
  stage: tests
  services:
    - mongo
  script:
    - cd src
    - npm install && node_modules/.bin/bower --allow-root install
    - npm t
  only:
    - branches

Docker build:
  image: docker:git
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_REF_NAME
  environment: master
  only:
    - master
  except:
    - tags

Docker release:
  image: docker:git
  stage: release
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE
    - docker build -t $CI_REGISTRY_IMAGE:$CI_BUILD_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_BUILD_TAG
    - docker tag $CI_REGISTRY_IMAGE:$CI_BUILD_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  environment: production
  only:
    - tags
    - triggers

Github and Docker Hub:
  image: ubuntu
  stage: mirror
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update && apt-get install --no-install-recommends -y git openssh-client curl
    - mkdir -p ~/.ssh
    - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
    - ssh-keyscan -H github.com > ~/.ssh/known_hosts
    - chmod -R 0600 ~/.ssh/
    - git remote add github git@github.com:orobardet/3dptools.git
    - git fetch github
    - git push github --mirror "$CI_BUILD_REF_NAME" -f
    - curl -k "https://registry.hub.docker.com/u/orobardet/3dptools/trigger/5342d440-a38f-4510-b0a2-15aa1e59f339/"
  when: manual
  only:
    - master
