version: '2'

services:
  mongo:
    volumes:
    # change the first part before ':' below to any path you want data to persist
    - "./docker-volumes/mongo/db:/data/db"

    # Uncomment the 'mongo-express' block if you want to setup the mongo-express web gui admin tool
#  mongo-express:
#    image: mongo-express
#    networks:
#      - backend
#      - traefik
#    depends_on:
#      - mongo
#    # Uncomment the 'ports' block to expose the port on your host
#    #ports:
#    # Change the 8090 below to any other available port on your host
#    #- "8090:80"
#    labels:
#      traefik.enable: "true"
#      traefik.backend: "mongo-express-3dpt"
#      traefik.docker.network: "traefik"
#    # Replace 'container.my.fqdn' with the hostname you want to use to access mongo-express
#      traefik.frontend.rule: "Host:container.my.fqdn"

  3dptools:
    image: 3dptools-dev
    build: .
    # This will start the application using nodemon, with automatic node restart when a file change.
    # Comment if you want to start the application normally
    command: npm run startmon
    # Uncomment the 'networks' block if you want to use Traefik to access the application
    #networks:
    #  - traefik
    # Else uncomment the 'ports' block to expose the port on your host
    #ports:
    # Change the first 3000 below to any other available port on your host
    #- "3000:3000"
    volumes:
      - ./src:/3dptools
      - ./CHANGELOG.md:/CHANGELOG.md
    environment:
      NODE_ENV: "development"
      DEBUG: "3DPTools,3DPTools:*"
      DEBUG_COLORS: 1
      changelog__filePath: "../CHANGELOG.md"
    labels:
      traefik.enable: "true"
      traefik.backend: "3dptools"
      traefik.docker.network: "traefik"
    # Replace 'container.my.fqdn' with the hostname you want to use to access the application
      traefik.frontend.rule: "Host:container.my.fqdn"

# Uncomment the 'networks' block if you want to use Traefik to access the application
#networks:
#  traefik:
#    external: true
