version: '3'

services:
  mongo:
    image: mongo:4
    networks:
      - backend
    volumes:
    - "./docker-volumes/mongo/db:/data/db"

  redis:
    image: redis:alpine
    networks:
      - backend

  3dptools:
    image: orobardet/3dptools
    networks:
      - backend
      - frontend
    depends_on:
    - mongo
    - redis
    ports:
    - "3000:3000"
    environment:
      database__user: ""
      database__pass: ""

networks:
  backend:
  frontend: